# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
      build_cli:
        generate_for:
          include:
          - test/src/**

builders:
  build_cli:
    target: noop
    import: "package:build_cli/build_cli.dart"
    builder_factories: ["createBuilderForCliGenerator"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
